name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v3

      - name: Deployment

        uses: appleboy/ssh-action@v0.1.7

        with:
          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}

          script: |
            cd /var/www/e_shop_backend
            git pull origin master || { echo 'Git pull failed'; exit 1; }
            npm i || { echo 'NPM install failed'; exit 1; }
            pm2 restart all || { echo 'PM2 restart failed'; exit 1; }